### ISSUE TITLE
Kirchenge and Grossmunster datasets

### ISSUE THREAD

**Issue by javrtg** [vlarsson/radialsfm#3]
Hi @vlarsson,

Thanks a lot for open-sourcing this work. I am interested in using
the Kirchenge and Grossmunster datasets referenced in the Tangent Sampson Error work [1].

I noticed that the Grossmunster dataset is linked in the readme, and I was able to download
the images and database. However, I could not find the (pseudo) ground-truth extrinsic
parameters. Are the ground-truth poses mentioned in [1] derived from the two_view_geometries of the database?

Additionally, is the Kirchenge dataset available?

Thank you in any case :)

[1] Tangent Sampson Error: Fast Approximate Two-view Reprojection Error for Central Camera Models, Terekhov, Mikhail and Larsson, Viktor, ICCV 2023.

**Comment by vlarsson** [comment]
Hey,
I've saved the pairs (and matches) we used the Tan. Sampson evaluation here

http://vision.maths.lth.se/viktor/posebench/relative/fisheye_grossmunster_4342.h5
http://vision.maths.lth.se/viktor/posebench/relative/fisheye_kirchenge_2731.h5

The camera intrinsics should be there as well.  You can checkout how to load it here https://github.com/vlarsson/posebench/blob/main/relative_pose.py

The GT poses are not from the two_view_geometries table, but come from the SfM reconstruction. Let me know if you have any trouble getting the data out :)

Regarding the kirchenge images, I will upload them shortly.

Edit: you can download the images here
http://vision.maths.lth.se/viktor/posebench/relative/grossmunster-images.zip
http://vision.maths.lth.se/viktor/posebench/relative/kirchenge-images.zip
I think these are all at least.

**Comment by javrtg** [comment]
Thanks a lot for the prompt response, data and usage info! :)

Just to confirm, I've noticed that the .h5 files contain relative pose ground-truth. Is the "Structure-from-Motion ground-truth", mentioned in [1], currently not included in the dataset?

**Comment by vlarsson** [comment]
Yes, this should be the SfM ground truth. The h5 files were setup after the deadline, but I think they should contain exactly the pairs, matches and GT that were used in the experiments.

**Comment by javrtg** [comment]
Perfect, the data is going to be really useful for my work :) Thanks a lot!
